name: Tekst-API code formatting and style checks

on:
  push:
    branches:
      - development
      - main
    paths:
      - "Tekst-API/tekst/**"
      - "Tekst-API/tests/**"
      - "Tekst-API/pyproject.toml"
      - "Tekst-API/uv.lock"
      - ".github/workflows/api-style.yml"
  pull_request:
    branches:
      - development
    paths:
      - "Tekst-API/tekst/**"
      - "Tekst-API/tests/**"
      - "Tekst-API/pyproject.toml"
      - "Tekst-API/uv.lock"
      - ".github/workflows/api-style.yml"
  workflow_dispatch:

jobs:
  checks:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./Tekst-API

    steps:
      - uses: actions/checkout@v5
      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          version: "0.9.11"
          enable-cache: true
      - name: Install Python
        uses: actions/setup-python@v6
        with:
          python-version-file: "./Tekst-API/pyproject.toml"
      - name: Install dependencies
        run: uv sync
      - name: Cancel on setup error
        if: failure()
        uses: andymckay/cancel-action@0.5
      - name: Lint code base
        if: always()
        run: uv run ruff check . --extend-select N
      - name: Check code formatting
        if: always()
        run: uv run ruff format . --check
